import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { registerAnalyzeProgressionTool } from './analyze-progression/index.js';
import { registerAnalyzeVoiceLeadingTool } from './analyze-voice-leading/index.js';
import { registerDetectKeyTool } from './detect-key/index.js';
import { registerGenerateArpeggioMidiTool } from './generate-arpeggio-midi/index.js';
import { registerGenerateBasslineMidiTool } from './generate-bassline-midi/index.js';
import { registerGenerateDrumPatternMidiTool } from './generate-drum-pattern-midi/index.js';
import { registerGenerateProgressionMidiTool } from './generate-progression-midi/index.js';
import { registerGenerateScaleMidiTool } from './generate-scale-midi/index.js';
import { registerGetChordTool } from './get-chord/index.js';
import { registerGetDiatonicChordsTool } from './get-diatonic-chords/index.js';
import { registerGetIntervalTool } from './get-interval/index.js';
import { registerGetKeyTool } from './get-key/index.js';
import { registerGetModeTool } from './get-mode/index.js';
import { registerGetNoteInfoTool } from './get-note-info/index.js';
import { registerGetProgressionTool } from './get-progression/index.js';
import { registerGetScaleTool } from './get-scale/index.js';
import { registerListCadencesTool } from './list-cadences/index.js';
import { registerListVoicingsTool } from './list-voicings/index.js';
import { registerSearchModesTool } from './search-modes/index.js';
import { registerSearchProgressionsTool } from './search-progressions/index.js';
import { registerSuggestSubstitutionsTool } from './suggest-substitutions/index.js';
import { registerTransposeProgressionTool } from './transpose-progression/index.js';
import { registerTransposeTool } from './transpose/index.js';

export function registerAllTools(server: McpServer): void {
  registerGetNoteInfoTool(server);
  registerGetIntervalTool(server);
  registerGetScaleTool(server);
  registerGetChordTool(server);
  registerTransposeTool(server);
  registerGetKeyTool(server);
  registerAnalyzeProgressionTool(server);
  registerDetectKeyTool(server);
  registerTransposeProgressionTool(server);
  registerGetDiatonicChordsTool(server);
  registerSuggestSubstitutionsTool(server);
  registerAnalyzeVoiceLeadingTool(server);
  registerGenerateProgressionMidiTool(server);
  registerGenerateScaleMidiTool(server);
  registerGenerateArpeggioMidiTool(server);
  registerGenerateBasslineMidiTool(server);
  registerGenerateDrumPatternMidiTool(server);
  registerSearchProgressionsTool(server);
  registerGetProgressionTool(server);
  registerSearchModesTool(server);
  registerGetModeTool(server);
  registerListVoicingsTool(server);
  registerListCadencesTool(server);
}
