name: Mirror to GitLab

on:
  push:
    branches: ['**']
    tags: ['**']
  delete:
  workflow_dispatch:

concurrency:
  group: mirror-gitlab
  cancel-in-progress: false

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Load 1password secrets
        uses: 1password/load-secrets-action@v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITLAB_TOKEN: 'op://mcp42-app/github-secrets/GITLAB_TOKEN'

      - name: Mirror to GitLab
        run: |
          git clone --mirror "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" repo.git
          cd repo.git
          git push --mirror "https://oauth2:${GITLAB_TOKEN}@gitlab.com/alextermure/mcp42.git"
